apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-pvc
    namespace: web
spec:
   accessModes:
      - ReadWriteOnce
   volumeMode: Filesystem
   resources:
      requests:
        storage: 256Mi
   storageClassName: local-storage